FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libpng-dev \
    zlib1g-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    && docker-php-ext-install gd pdo pdo_mysql mysqli \
    && a2enmod rewrite

WORKDIR /var/www/html
COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html