export const games = [
  {
    id: 'The Crucible Laments',
    titulo: 'The Crucible Laments',
    description: 'lorem',
    ruta: 'TheCrucibleLaments',
    iconKey: null,
    iconSrc: '/gamesImg/CrucibleLamentBanner.jpg',
    tipoIcono: "image",
    componente: 'FifaPage',
    description: '',
    iconGame: '/logoVGS.svg',
    requererimentsLows: 'Ryzen 5 3600, 8GB RAM, 128GB SSD',
    requererimentsHigh: 'Ryzen 9 5900X, 16GB RAM, 256GB SSD',
    imgGame: '/gamesImg/CrucibleLamentBanner.jpg',
  },
  {
    id: 'minecraft',
    titulo: 'Minecraft',
    ruta: 'minecraft',
    iconKey: null,
    iconSrc: '/icons/minecraft.svg',
    tipoIcono: "image",
    componente: 'MinecraftPage',
    description: 'test',
    iconGame: '/logoVGS.svg',
    requererimentsLows: 'Ryzen 5 3600, 8GB RAM',
    requererimentsHigh: 'Ryzen 9 5900X, 16GB RAM',
    imgGame: '/logoVGS.svg',
  },
  {
    id: 'tetris',
    titulo: 'Tetris',
    ruta: 'tetris',
    iconKey: null,
    iconSrc: '/icons/tetris.svg',
    tipoIcono: "image",
    componente: 'TetrisPage',
    description: 'test',
    iconGame: '/logoVGS.svg',
    requererimentsLows: 'Ryzen 5 3600, 8GB RAM',
    requererimentsHigh: 'Ryzen 9 5900X, 16GB RAM',
  },
];
