export const games = [
  {
    id: 'The Crucible Lament',
    titulo: 'The Crucible Lament',
    ruta: 'TheCrucibleLament',
    iconKey: null,
    iconSrc: '/gamesImg/CrucibleLamentBanner.jpg',
    tipoIcono: "image",
    componente: 'FifaPage',
    subtitulos: ['Combate', 'Exploración y Mundo', 'Sistema de Progresión'],
    descriptions: [
      'Combate exigente basado en la resistencia, la precisión y la gestión de stamina. Incluye un sistema de "parry" con ventana estricta (como Lies of P) que recompensa la maestría, permitiendo romper la guardia de los enemigos para golpes críticos. Esquivar y bloquear son cruciales',
      'Mundo semi-abierto interconectado, pero con zonas vastas y diversas que se sienten como "mini-mundos abiertos" dentro de sí (como regiones de Elden Ring). La progresión es no lineal, con numerosos secretos, caminos ocultos y atajos que conectan las áreas.',
      'Los "Ecos" (equivalente a almas/runas) se obtienen al derrotar enemigos y se usan para subir de nivel atributos (Vitalidad, Fuerza, Destreza, Voluntad, etc.) en puntos de descanso. Se complementa con un sistema de "Reliquias" (similar a los Amuletos de Hollow Knight) que otorgan habilidades pasivas o activas únicas y deben ser equipadas en ranuras limitadas.'
    ],
    iconGame: '/gamesImg/CrucibleLamentIcon.png',
    requererimentsLows: 'Ryzen 5 3600, 8GB RAM, 128GB SSD',
    requererimentsHigh: 'Ryzen 9 5900X, 16GB RAM, 256GB SSD',
    imgGame: '/gamesImg/CrucibleLamentBanner.jpg',
  },
  {
    id: 'Echos of Contention',
    titulo: 'Echos of Contention',
    ruta: 'EchosOfContention',
    iconKey: null,
    iconSrc: '/gamesImg/EchosOfContentionBanner.jpg',
    tipoIcono: "image",
    componente: 'FifaPage',
    subtitulos: ['Mapa', 'Roles y Héroes', 'Duración de Partida'],
    descriptions: [
      'Mapa asimétrico, pero con un sistema de sendas (carriles) muy marcado y objetivo primario (el Nexus/Ancestro). Incluirá Runas y Santuarios en puntos clave que dan buffs temporales o teletransportes estratégicos.',
      'Héroes/Arcontes con roles más definidos (Tanque, Asesino, Mago, Tirador, Soporte, Jungla). Sin embargo, cada Arconte tendrá tres Atributos Primarios (Fuerza, Agilidad, Sabiduría) con efectos secundarios únicos (como en DOTA 2) que permiten builds de objetos más flexibles.',
      'Diseño de mapa y objetivos que incentiven el final de la partida. La regeneración de vida de las estructuras aliadas es mínima o nula, y hay "Objetivos de Ascensión" (criaturas neutrales súper poderosas, estilo Barón Nashor de LoL) que dan grandes ventajas para el push de final de partida.'
    ],
    iconGame: '/gamesImg/EchosOfContentionIcon.png',
    requererimentsLows: 'Ryzen 5 5600, 12GB RAM, 128GB SSD',
    requererimentsHigh: 'Ryzen 9 5900X, 16GB RAM, 260GB SSD',
    imgGame: '/gamesImg/EchosOfContentionBanner.jpg',
  },
  {
    id: 'Visionless',
    titulo: 'Visionless',
    ruta: 'Visionless',
    iconKey: null,
    iconSrc: '/gamesImg/VisionlessBanner.jpg',
    tipoIcono: "image",
    componente: 'FifaPage',
    subtitulos: ['Descripcion', 'Combate', 'Exploracion del Mundo'],
    descriptions: [
      'Pon a prueba tus sentidos en una partida competitiva, donde apenas podrás ver a tus rivales. Debes escuchar con atención y localizarlos antes de que sea demasiado tarde. Con algo de sonar sabrás dónde estás, pero ¿recordarás dónde está todo?',
      'Ágil, preciso y lleno de tensión. Domina diferentes estilos de enfrentamiento, aprovecha tu entorno y usa el sonido como tu mejor arma. Cada movimiento puede revelar tu posición, así que actúa con estrategia y determina cuándo atacar o esconderte.',
      'Sumérgete en escenarios misteriosos donde la visibilidad es mínima, pero la ambientación lo dice todo. Descubre secretos ocultos, rutas alternativas y elementos que alteran tu percepción del espacio. La oscuridad no solo te desafía: también te invita a explorarla.',
    ],
    iconGame: '/gamesImg/VisionlessIcon.svg',
    requererimentsLows: 'Ryzen 3 5600g, 6GB RAM, 30GB SSD',
    requererimentsHigh: 'Ryzen 5 5900X, 12GB RAM, 50GB SSD',
    imgGame: '/gamesImg/VisionlessBanner.jpg',
  },
  {
    id: 'Lost In Space',
    titulo: 'Lost In Space',
    ruta: 'LostInSpace',
    iconKey: null,
    iconSrc: '/gamesImg/LostInSpaceBanner.png',
    tipoIcono: "image",
    componente: 'FifaPage',
    subtitulos: ['Descripcion', 'Combate', 'Exploracion del Mundo'],
    descriptions: [
      'Parece que no encuentras a nadie en el edificio, pero estaban aquí justo antes de que te durmieras. Tienes que buscar una salida o información sobre lo que ocurrió mientras estabas inconsciente. Aparecen cosas nuevas que antes no estaban; es como si alguien las hubiera dejado allí para ti.',
      'Prepárate para defenderte: el peligro puede acechar en cualquier esquina y el ambiente extraño aumenta la tensión. Tus habilidades serán puestas a prueba en enfrentamientos impredecibles, donde cada objeto nuevo puede significar una amenaza o una oportunidad.',
      'Recorre pasillos desconocidos y habitaciones enigmáticas del edificio. La arquitectura ahora parece diferente, como si se hubiera transformado mientras estabas inconsciente. Descubre las pistas y elementos que otros han dejado atrás y conecta las piezas para entender el cambio que ha sucedido.',
    ],
    iconGame: '/gamesImg/LostInSpaceIcon.svg',
    requererimentsLows: 'Ryzen 3 5600g, 6GB RAM, 30GB SSD',
    requererimentsHigh: 'Ryzen 5 5900X, 12GB RAM, 50GB SSD',
    imgGame: '/gamesImg/LostInSpaceBanner.png',
  },
];
